export default {
    LOGO: require('../assets/images/logo-platesaver.png'),
    w1: require('../assets/images/chef.png'),
    donation: require('../assets/images/donate-icon.png'),
    notification: require('../assets/images/notification-icon.png'),
    profilepic: require('../assets/images/profile-icon.png'),
    preference: require('../assets/images/plate-icon.png'),
    whatscooking: require('../assets/images/wgatscooking.jpg'),
    mealplan: require('../assets/images/mealplan.jpg'),
    cartcomp: require('../assets/images/cartcompaninon.jpeg'),
    pantrypro: require('../assets/images/pantrypro.jpeg'),
    i1: require('../assets/images/i1.jpg'),
    i2: require('../assets/images/i2.jpg'),
    i3: require('../assets/images/i3.jpg'),
}